version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: 'tsed-example-typeorm/server:latest'
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
  postgres:
    image: 'postgres:9.6.1'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
